### ISSUE TITLE
Where can I find your paper?

### ISSUE THREAD

**Issue by seki18** [Ilmosal/QDBN#1]
I'd like to read your paper. Thank you

**Comment by Ilmosal** [comment]
Hi! 

The thesis can be downloaded from here https://helda.helsinki.fi/handle/10138/329796!

**Comment by seki18** [comment]
Thank you. That’s very helpful

**Comment by seki18** [comment]
> Hi!
> 
> The thesis can be downloaded from here https://helda.helsinki.fi/handle/10138/329796!

Thank you. That’s very helpful
